{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bioset
  version: {{ version|replace("-", "_") }}

source:
  fn: bioset_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/bioset_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bioset/bioset_{{ version }}.tar.gz
  sha256: 31f0509f352e8881113929bfb7ea060566938cce4a02178314a446866a846c97

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >=0.7.4
    - r-magrittr >=1.5
    - r-rlang >=0.1.2
    - r-tibble >=1.3.4
    - r-tidyr >=0.7.1
  run:
    - r-base
    - r-dplyr >=0.7.4
    - r-magrittr >=1.5
    - r-rlang >=0.1.2
    - r-tibble >=1.3.4
    - r-tidyr >=0.7.1

test:
  commands:
    - $R -e "library('bioset')"           # [not win]
    - "\"%R%\" -e \"library('bioset')\""  # [win]

about:
  home: https://github.com/randomchars42/bioset
  license: MIT
  summary: Functions to help dealing with raw data from measurements, like reading and transforming
    raw values organized in matrices, calculating and converting concentrations and
    calculating precision of duplicates / triplicates / ... . It is compatible with
    and building on top of some 'tidyverse'-packages.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
