appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RET9zUoUJhvGPO8GB3nSF4wvrHFkz8Bh1cOmUv+Gn7D/GqMXlIeAUEOSFBv1CyTV2D1BV45KJwWclg/wFauuXtXORdHlepIMlqaLsSJgzWEgvX7FIklp3eXkOy+ENFweVsqGRIlIhJHqw3H7ZXygZDdQc0jAfSKXeXxWhqDz8EJGmj4kRcD/2E5ODOitnAAypE5xQ7KGEmo/KffxYV+h90xXJpVKXxVN+qS2AjWgtshGO6/5ZMC3isbXyOG7z8z4QqWFRwG/7iWgnu2/a4v/BjTarRvmHJ8VR92h4y9S+kDHD5VZGlDx2i9ACKPw2oITZA6UneweFwQiSCqRdXUHh248W/wULHPoQTXVRgkIwPNa2JB2LBGcfYw38N+F5814MlYp99LXEMCvxIwhcEKpwxVj+v2zq0LksdiU7Fgv8iLLAhj7dK3+cos/wvRJUJrRM/31C6DG747b+T/ZPJAQ8CztkPBG900wUx2mPvGiqIWL6FkWTUT57S0qSSf589G9Xu8/CUp7GA06aJQXb9AiBkjo97IqHV6iSRFjdlDKJ0V7olYRl7iyae+aVXRomi9WwFH8CWQOLTRrcvKc/dV1AEp1LmShLUGA+GLDBXsXDF6vpaAh8+sqQQXGvuMJjm9MpQY0sAExw42ZGHmxZSXewMc6tONdTPgcbD8zIDg5NBQ=}
